UiLink
js-tasks-ru/vue-20211004_maxim-b pull request #9
Opened 2021-11-02 20:32 UTC by MaximBurcev

2021-11-02 20:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-02 20:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-11-04 12:15 UTC, ShGKme requested changes
Требуются небольшие доработки

2021-11-04 12:15 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </template>
`tag` лучше явно описать, как параметр компонента. Это не просто атрибут, который нужно пробросить дальше, а непосредственно параметр компонента, определяющий его работу.

2021-11-04 12:15 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </template>
Вы используете три `v-if` для вывода трёх вариантов ссылки. Это не только делает реализацию длинной, но и не позволяет использовать другие элементы (например, `nuxt-link` для ссылок во фреймворке `nuxt`.

Вместо этого требуется использовать динамический компонент `<component :is=...>`

2021-11-04 12:15 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </template>
Вручную передавать атрибуты не требуется, они будут наследоваться автоматически.

2021-11-04 12:15 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </template>
`this` в шаблоне не требуется.

2021-11-05 20:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-05 20:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-06 11:07 UTC, ShGKme requested changes
Требуется ещё одна маленькая правка

2021-11-06 11:07 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
>  </template>
Не заметил в прошлом review. Потерялся `class="link"`.

2021-11-06 12:59 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-06 13:03 UTC, MaximBurcev commented on 06-wrappers/01-UiLink/components/UiLink.vue
>  </template>
Не совсем понимаю. class="link" есть же у <component>

2021-11-06 13:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-11-06 15:06 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
>  </template>
Прошу прощения, это я куда-то не туда посмотрел, всё на месте...

2021-11-06 15:18 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-11-06 15:18 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +    }
В таком решении `buttonType` будет иметь значение `button`, даже если явно передан `type="submit"`. Решение в итоге всё равно будет работать, потому что явно переданный `type="submit"` при наследовании атрибута имеет больший приоритет, чем установленный в компоненте `:type="buttonType"`. Но на мой взгляд это может быть не очевидно, значение `buttonType` не соответствует ожидаемому. Вместо проверки `this.$attrs.type !== 'button'` я бы оставил просто проверку, что `this.$attrs.type` не передан.

2021-11-06 15:18 UTC, merged